object Libraries {
    val activityCompose = "androidx.activity:activity-compose:${Versions.activityCompose}"
    val androidCore = "androidx.core:core-ktx:${Versions.androidCore}"
    val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    val material = "com.google.android.material:material:${Versions.material}"

    val coil = "io.coil-kt:coil-compose:${Versions.coil}"
    val constraintCompose = "androidx.constraintlayout:constraintlayout-compose:${Versions.constraintCompose}"
    val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutinesTest}"
    val elmyr = "com.github.xgouchet.Elmyr:core:${Versions.elmyr}"
    val jUnitJupiterEngine = "org.junit.jupiter:junit-jupiter-engine:${Versions.jUnitEngine}"
    val composeJUnit4 = "androidx.compose.ui:ui-test-junit4"
    val splashScreen = "androidx.core:core-splashscreen:${Versions.splashScreen}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val retrofitMoshiConverter = "com.squareup.retrofit2:converter-moshi:${Versions.retrofit}"
    val moshi = "com.squareup.moshi:moshi:${Versions.moshi}"
    val moshiKotlin = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    val mockK = "io.mockk:mockk:${Versions.mockK}"
    val mockKAndroid = "io.mockk:mockk-android:${Versions.mockK}"
    val mockKJVMAgent = "io.mockk:mockk-agent-jvm:${Versions.mockK}"
    val navigationCompose = "androidx.navigation:navigation-compose:${Versions.navigationCompose}"
    val compose = "androidx.compose:compose-bom:${Versions.compose}"
    val composeUi = "androidx.compose.ui:ui"
    val composeMaterial = "androidx.compose.material:material"
    val composeAnimation = "androidx.compose.animation:animation-graphics"
    val composeTooling = "androidx.compose.ui:ui-tooling"

    val lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    val viewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.viewModel}"
}